name: Preview

on:
  push:
    branches: ['master']

jobs:
  fingerprint:
    type: fingerprint
    environment: preview

  get_build:
    needs: [fingerprint]
    type: get-build
    params:
      platform: android
      profile: preview
      distribution: internal
      fingerprint_hash: ${{ needs.fingerprint.outputs.android_fingerprint_hash }}

  build:
    needs: [get_build]
    if: ${{ !needs.get_build.outputs.build_id }}
    type: build
    env:
      EAS_USE_CACHE: '1'
    params:
      platform: android
      profile: preview

  update:
    needs: [get_build]
    after: [build]
    type: update
    params:
      channel: preview
